lab2:
 # Run exercise 1.5
	echo "Running exercise 1.5"
	g++ -o l2_operand l2_operand.cpp
	./l2_operand

	echo "Running exercise 1.11 while loop"
	g++ -o l2_forloop_range l2_forloop_range.cpp
	./l2_forloop_range

	echo "Running exercise 1.11 while loop"
	g++ -o l2_while_range l2_while_range.cpp
	./l2_while_range
